[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "smri-fm"
dynamic = ["version"]
description = "MedARC sMRI foundation model"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "braceexpand",
    "datasets",
    "einops",
    "huggingface-hub",
    "ipython",
    "jaxtyping",
    "jupyter",
    "matplotlib",
    "nibabel",
    "numpy",
    "omegaconf",
    "pandas",
    "pre-commit",
    "pytest",
    "pyyaml",
    "s3fs",
    "scikit-learn==1.8.0",
    "scipy",
    "seaborn",
    "SynthSeg",
    "tabulate",
    "templateflow",
    "timm",
    "torch==2.8.0",
    "torchvision",
    "tqdm",
    "wandb",
    "webdataset",
]


[tool.uv.sources]
SynthSeg = { git = "https://github.com/MedARC-AI/SynthSeg.git", rev = "2690d9ac9ae28323d03043406cd21db0a8741547" }

[tool.setuptools_scm]
version_file = "src/_version.py"

[tool.setuptools.package-data]
fomo_tune = ["assets/*.npy"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F722"]

[tool.pytest.ini_options]
norecursedirs = ["third_party", ".scratch"]
