output_root: output
name_prefix: eval_linear
model_kwargs:
  ckpt_path: null
dataset_kwargs:
  repo_id: medarc/adni_eval
  token: null
  cache_dir: null
task_name: sex
# sMRI preprocessing input size (must match the checkpoint's img_size).
img_size: [208, 240, 208]
map_workers: 4
num_workers: 4
batch_size: 4
Cs: 10
cv_metric: bacc
max_iter: 1000
metrics: [acc, f1, bacc]
amp: true
device: cuda
seed: 4466
