# @package _global_
defaults:
  - /default_linear_probe
  - /hardware/cpu@hardware
  - /model/smri_mae@model
  - _self_

# For linear_probe, using the same as for Task 1
task: CLS002_FOMO26_Infarct_FLAIR

checkpoint_path: /Users/lukasecerovic/Documents/repos/sMRI/smri-fm/.scratch/pretrained_mae_checkpoint/checkpoint-last-asparagus-NEW.ckpt

data:
  train_split: split_80_10_10
  test_split: TEST_80_10_10
  fold: 0

hardware:
  accelerator: cpu
  num_devices: 1
  num_workers: 2
  precision: 32-true
  compile_mode: null

training:
  batch_size: 1
  epochs: 1
  max_epochs: 1
  limit_train_batches: 2
  limit_val_batches: 1
  check_val_every_n_epoch: 1
  target_size: [208, 240, 208]
  warmup_epochs: 0

logger:
  wandb_logging: false
  log_every_n_steps: 1

model:
  _cls_net:
    _target_: asparagus_bridge.models_smri_mae.SmriMaeClsRegBackbone
    img_size: [208, 240, 208]
    patch_size: 8
    pool: cls   # or mean
